#!/bin/sh

CURRENT_DIR=$(dirname "$0")
. "$CURRENT_DIR/quiet"
. "$CURRENT_DIR/colors"

cores=$(grep -c ^processor /proc/cpuinfo 2>/dev/null)
[ "$cores" -eq "0" ] && cores=1
threshold="${cores:-1}.0"

echo

above_threshold=$(echo "$(cut -f1 -d ' ' /proc/loadavg) < $threshold" | bc)
if [ "$above_threshold" -eq 1 ]; then
    python3 "$CURRENT_DIR/sysinfo.py"
else
    echo " System information disabled due to load higher than $threshold"
fi

printf "\n"
