#!/bin/bash

. /etc/update-motd.d/colors

if [[ $MOTD_NEED_UPGRADE -gt 0 ]]; then
    printf $LIGHT_RED
    printf "  You have %s packages waiting for upgrades." "$n"
    printf $NONE"\n\n"
fi
if [[ $MOTD_NOT_NEEDED -gt 0 ]]; then
    printf $YELLOW
    printf "  You have %s packages that were automatically installed and are not needed anymore." "$n"
    printf $NONE"\n\n"
fi
