#!/bin/sh

CURRENT_DIR=$(dirname "$0")
. "$CURRENT_DIR/quiet"
. "$CURRENT_DIR/colors"

n=$(apt --quiet --quiet list --upgradable 2>/dev/null | wc -l)
if [ "$n" -gt 0 ]; then
    printf "%b  You have %s packages waiting for upgrades.%b\n\n" "$LIGHT_RED" "$n" "$NONE"
fi
n=$(apt --quiet --quiet --just-print autoremove 2>/dev/null | grep -c Remv)
if [ "$n" -gt 0 ]; then
    printf "%b  You have %s packages that were automatically installed and are not needed anymore.%b\n\n" "$YELLOW" "$n" "$NONE"
fi
