#!/bin/sh

set -e

case "$1" in
    remove)
        rm /etc/motd
        if [ -f /etc/motd-dist ]; then
            mv /etc/motd-dist /etc/motd
        else
            cat > /etc/motd << EOF

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
EOF
        fi
        ;;

    purge | upgrade | failed-upgrade | abort-upgrade | abort-install | disappear) ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
