#!/bin/sh

set -e

case "$1" in
    configure)
        mv /etc/motd /etc/motd-dist
        ln -s /var/run/motd /etc/motd
        ;;

    abort-upgrade | abort-remove | abort-deconfigure) ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
